### ISSUE TITLE
[CFP] 1º meetup ReactJS Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/meetups#1]
# [CFP] - 1º meetup ReactJS Ceará
**[Agenda Edu](https://www.google.com/maps/place/Agenda+Edu/@-3.7496198,-38.5057294,15z/data=!4m2!3m1!1s0x0:0x5e15d77ff15bcd89?sa=X&ved=2ahUKEwi51KqN9rrmAhWOHbkGHcyKCm4Q_BIwDnoECAwQCA), 18 janeiro 2020, de 9h às 12h** 

 
Submeta sua talk(máximo  de 40 minutos) através dos comentários seguindo o formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**
 
**OBS:** Para este meetup serão escolhidas 4 talks.

**DICA:**

Algumas sugestões da comunidade sobre tópicos interessantes para talks.
https://docs.google.com/spreadsheets/d/15vhCbD6LZwJageJO0OJa9IRFvE4zzBCMGod48UDqUn8/edit?usp=sharing

**Comment by cicerohen** [comment]
Bem-vindo ao mundo ReactJS
Duração(30:00)
Um resumo sobre o ecossistema ReactJS, motivações para o uso, suas principais APIs, conceitos, etc, com foco em quem está começando a usar a ferramenta.

**Comment by cicerohen** [comment]
**Gerenciando efeitos colaterais no Redux**

*Duração 40 minutos*

Nessa talk iremos falar sobre:
* Fundamentos do Redux/Flux;
* Side-effects, o que são e porquê controlá-los.

**Comment by cicerohen** [comment]
**Context API e Redux**

*Duração 30 minutos*

Nessa talk iremos discutir as diferentes abordagens para armazenamento de estado, seus contextos de uso, etc.

**Comment by hileomsi** [comment]
**Storybook: Aumentando a maturidade e documentação do seu projeto react.**
_Duração: 40 minutos_

O storybook veio com o objetivo de documentar e facilitar a construção de componentes, isolando em seu contexto toda a forma visual do componentes trazendo produtividade de muitas formas e agregando maturidade ao projeto. Vamos conversar sobre como usa-lo da melhor forma e como esse resolver algum problemas do design.

**Comment by rubenspgcavalcante** [comment]
**É possível viver sem Redux? Extraindo o máximo dos Hooks.** 
_Duração: 30 minutos_

Como viver sem o Redux? Que tal substituí-lo por soluçōes mais simples como useState e no mais complexo dos casos, useReducer com Context API? E olha só, tudo isso é nativo do React!
Nessa apresentação vamos cobrir os use cases em que o Redux parece simplesmente obrigatório e provaremos que sim, é possível gerenciar dados e side-effects apenas utilizando Hooks :)

**Comment by rubenspgcavalcante** [comment]
**Introdução aos Monorepos** 
_Duração: 30 minutos_

Versão em PT brazuca da minha apresentação no React Berlin:
https://www.youtube.com/watch?v=AjVGoJNV-bE

O que são monorepositorios e para que servem? Como estrutura-los, quais ferramentas utilizar para facilitar sua manutenção e como evitar erros comuns em projetos com tal infraestrutura.
Nessa apresentação vamos cobrir o básico sobre monorepositorios JS/NodeJS

**Comment by cicerohen** [comment]
**Enyzme, react-testing-library e Jest**

Duração: 30 minutos

Nessa talk iremos discutir os diferentes propósitos das ferramentas, e claro, com exemplos práticos. :D

**Comment by andersonmadeira** [comment]
_**CSS-In-JS**_

_Duração:_ 30 minutos

_Abordagens para CSS em JavaScript usando React_

Vamos discutir motivações e boas práticas de algumas abordagens de estilizar componentes de maneira encapsulada e restrita ao componente com inline styles e styled-components

**Comment by andersonmadeira** [comment]
**Code Splitting e Lazy Loading**

Duração: 30 minutos

Code Splitting e Lazy Loading de componentes React usando Lazy e Suspense

Vamos discutir ideias de como dividir código da aplicação (code splitting) e carregamento tardio (lazy loading) de componentes usando `lazy` e `Suspense`, como funcionam e o benefício que podem trazer pra nossas aplicações. Também veremos o uso disso com Rotas numa aplicação usando `react-router-dom`.

**Comment by andersonmadeira** [comment]
_**Introdução à Gatsby**_

_Duração: 40 minutos_

Introdução à geração de aplicações estáticas com Gatsby

"Gatsby é um gerador de sites moderno e rápido para o React.". Iremos ver como usar o Gatsby para gerar aplicações estáticas usando React e quais os benefícios que isso pode trazer para sua aplicação. Como caso de exemplo veremos como podemos criar um blog pessoal de tecnologia de maneira rápida, produtiva e fácil de manter.

**Comment by abdielbrilhante** [comment]
**Next.js, Razzle e `renderToString`: Server Side rendering com React**

Duração: 30 minutos

O uso de Server Side Rendering combinado a Single Page Applications vem crescendo nos últimos tempos, em particular devido às vantagens relacionadas a SEO e primeiro carregamento. Veremos algumas das diferentes opções disponíveis no ecossistema React para SSR, desde frameworks mais completos como Next.js até uma implementação mais direta, utilizando apenas o toolkit que o React oferece.

**Comment by abdielbrilhante** [comment]
**Memoização e performance em componentes e hooks**

Duração: 30 minutos

Dado o modelo de renderização do React, é útil (e algumas vezes necessário) dar atenção à frequência de atualização dos nossos components (e hooks). Veremos como o React nos ajuda a minimizar os *re-renders* com ferramentas como `React.memo` e `useMemo`, e também como funcionam os arrays de dependências presentes em outras hooks como `useEffect`.

**Comment by abdielbrilhante** [comment]
**De mixins a hooks**: um histórico dos *cross-cutting concerns* em React**

Duração: 40 minutos

Desde os remotos tempos de `React.createClass`, existiram diferentes modos de compartilhar **comportamento** entre diferentes componentes React. Veremos as diferentes soluções surgidas nos últimos anos, e como as hooks resolvem os problemas associados a implementações ainda bastante utilizadas pela comunidade, os *higher-order components* e as *render props*.

**Comment by cicerohen** [comment]
**Bricando de Lego com ReactJS**
Duração: 30 minutos

Nessa talk irei falar sobre componentização, reusabilidade, estruturação básica de projetos e conceitos funcionais aplicados ao ReactJS.

**Comment by cicerohen** [comment]
@hileomsi @rubenspgcavalcante falem comigo ai, mandem sinal de fumaça.

**Comment by rponte** [comment]
### Como Apresentar Código em Slides
LT de **15min**

Todo programador cedo ou tarde deverá **apresentar código em slides** no trabalho, na faculdade ou em um evento. O problema é que apresentar código é bem diferente de escrevê-lo no seu editor preferido. Basta escolher o tamanho de fonte errada e você perde toda a atenção do seu público.

Para você não cair nessa armadilha, eu apresento **5 dicas** matadoras para você apresentar código em slides de forma simples e eficiente. As dicas vão desde o tipo de fonte até tamanho e cores, o resultado surpreende.

**(apesar do tema estar não ter relação com React, se trata de uma soft-skill que pode ajudar a melhorar a qualidade das palestras)**

**Comment by cicerohen** [comment]
@rponte pra esse meetup as submissões já foram encerradas. :D Podemos colocar essa submissão pro próximo meetup :D

**Comment by cicerohen** [comment]
@rponte joga tua talk pro CFP do 2º meetup :D
