### ISSUE TITLE
[CFP] -  2º meetup React.js Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/meetups#2]
# [CFP] - 2º meetup ReactJS Ceará
**[Mobills Labs](https://www.google.com/maps/place/Mobills+Labs/@-3.7332644,-38.5093301,15z/data=!4m5!3m4!1s0x0:0x5aa4dda3dc92877a!8m2!3d-3.7332644!4d-38.5093301), 8 fevereiro 2020, de 9h às 12h** 

 
Submeta sua talk(máximo  de 40 minutos) através dos comentários seguindo o formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**
 
**OBS:** Para este meetup serão escolhidas as 3 talks

**DICA:**

Algumas sugestões da comunidade sobre tópicos interessantes para talks.
https://docs.google.com/spreadsheets/d/15vhCbD6LZwJageJO0OJa9IRFvE4zzBCMGod48UDqUn8/edit?usp=sharing

**Comment by jholdy** [comment]
Título: Reduxsauce com ducks e sagas
Duração(HH:MM)
Descrição: Falando um pouco mais da forma que uso o ducks e sagas com o Reduxsauce.
Descrição: vou explicar como usar o básico do ducks e dos sagas e a melhoria que é usar o Reduxsauce e milha forma para melhora tudo isso junto.

**Comment by IsmaelNascimento** [comment]
Título: React e AWS (Amazon Web Services)

Duração(HH:MM): 00:30

Descrição curta: Mostrando serviços CLOUD que irão ajudar o seu projeto !

Descrição longa: Nesta palestra irei falar de alguns serviços que irão lhe ajudar a escalar o seu projeto em React e como podem otimizar o seu tempo de desenvolvimento.

**Comment by cicerohen** [comment]
**Bricando de Lego com ReactJS**
Duração: 30 minutos

Nessa talk irei falar sobre **componentização**, **reusabilidade**, **estruturação** básica de projetos e **conceitos funcionais** aplicados ao ReactJS.

**Comment by IsmaelNascimento** [comment]
Título: Criando Realidade virtual com React

Duração(HH:MM): 00:30

Descrição curta: Como criar experiências em realidade virtual e 360 usando React

Descrição longa: Nesta palestra irei falar como você pode iniciar o uso do React 360, para criar aplicações 360 e realidade virtual para web, e visualizar em desktop, mobile e PC!!!!

**Comment by AbraaoAlves** [comment]
### React+Redux com Typescript
Duração: 40 minutos

Como se beneficiar de tipos em aplicações onde os dados tem um papel central no fluxo de execução? Não tenha mais dor de cabeça com tipos, ANYmore ...

Nessa palestra irei apresentar um conceito/filosofia de como manter seu codigo 100% tipado sem a necessidade de reescrever* seus tipos em cada modulo de codigo, facilitando o porte do seu app de JS para TS, ou apenas para manter seus contratos de dados intactos, desde seus reducers , passando pelos selectors, até seus components!

**Comment by cicerohen** [comment]
**Gerenciando efeitos colaterais no Redux**

*Duração 40 minutos*

Nessa talk iremos discutir:
* Fundamentos do Redux/Flux;
* Side-effects, o que são e os porquês de controlá-los.

**Comment by abdielbrilhante** [comment]
**Next.js, Razzle e `renderToString`: Server Side rendering com React**

Duração: 30 minutos

O uso de Server Side Rendering combinado a Single Page Applications vem crescendo nos últimos tempos, em particular devido às vantagens relacionadas a SEO e primeiro carregamento. Veremos algumas das diferentes opções disponíveis no ecossistema React para SSR, desde frameworks mais completos como Next.js até uma implementação mais direta, utilizando apenas o toolkit que o React oferece.

**Comment by cicerohen** [comment]
Usando Context API como alternativa prática ao store do Redux.
Duração 40 minutos

Nem sempre é preciso usar o Redux. Principalmente se você necessita apenas compartilhar estado e lógica entre componentes, por isso, nesta talk irei mostrar exemplos práticos de de uso do Context API e seus hooks como alternativa ao store do Redux.

**Comment by cicerohen** [comment]
**Insights sobre React.useCallback e memoização**

**Comment by BradHick** [comment]
### React Hooks: Performance pitfalls and how to avoid them
**Duração: 30 minutos**

> Alguma dicas de como evitar gargalos de performance usando os Hooks do React


Desde a estréia do versão 16 do React, os Hooks já são muito utilizados e comentados por toda a comunidade, mas assim como qualquer ferramenta, dependendo da forma como forem utilizados os Hooks, podemos gerar alguns problemas de desempenho em nossas aplicações. Vamos ver como evitar isso usando como exemplo alguns dos principais Hooks!

**Comment by rponte** [comment]
opa, 

já fechou a issue? hehe acho que perdi o time novamente.

será que tem espaço para uma apresentação de 15min (Lightning Talk)?

**Comment by vitormalencar** [comment]
Entao eu gostaria de saber tambem, queria submeter algo antes de voltar pra berlim
