### ISSUE TITLE
[CFP] - 3º meetup React.js Ceará

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/meetups#3]
# [CFP] - 3º meetup ReactJS Ceará
**[Mobills Labs](https://www.google.com/maps/place/Mobills+Labs/@-3.7332644,-38.5093301,15z/data=!4m5!3m4!1s0x0:0x5aa4dda3dc92877a!8m2!3d-3.7332644!4d-38.5093301), 4 abril 2020, de 14h às 17h** 

 
Submeta sua talk(máximo  de 30 minutos) através dos comentários seguindo o formato:

**Título**
**Duração(HH:MM)**
**Descrição curta**
**Descrição longa**
 
**DICA:**

Algumas sugestões da comunidade sobre tópicos interessantes para talks.
https://docs.google.com/spreadsheets/d/15vhCbD6LZwJageJO0OJa9IRFvE4zzBCMGod48UDqUn8/edit?usp=sharing

**Comment by robsonsilv4** [comment]
**Título**: _Existe vida além do Redux?_ Conheça o MobX.
**Duração**: 00:20 minutos.
**Descrição curta**: Introdução ao MobX, vantagens e como utilizá-lo.
**Descrição longa**: Será introduzido brevemente o que é e como funciona o MobX, além de conceitos de Reatividade. Será discutindo também as suas vantagens e comparações em relação ao Redux. Ao final será mostrado uma simples aplicação para exemplificar o que foi abordado.

**Comment by abdielbrilhante** [comment]
**GraphQL com Apollo Client**

Duração: 30 minutos

Uma das maiores vantagens apontadas por usuários do uso de GraphQL em relação a APIs REST é o tooling disponível para o uso tanto no backend, como (principalmente) no frontend. Nessa talk teremos uma introdução ao GraphQL e um pouco do ecossistema de ferramentas relacionadas para React, com foco em um dos principais clients disponíveis, o Apollo.

**Comment by hilderjares** [comment]
**Explorando o Next.js**

Duração: 30 minutos

O Next.js é uma iniciativa open source que tem como objetivo agilizar a construção de aplicações React, ele oferece um ambiente já configurado com o webpack. Ele também vem com componente de rotas pronto para ser utilizado, outra recurso bem interessante que ele possui é o server side rendering. Why not ?
